#!/usr/bin/env node

/** Generate a simple, single-column ATS-friendly DOCX from a tailored CV Markdown file. */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from 'docx';

export function normalizeCvTextForAts(value) {
  return String(value || '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/[*_`~]/g, '')
    .replace(/\u2014|\u2013/g, '-')
    .replace(/[\u201C\u201D\u201E\u201F]/g, '"')
    .replace(/[\u2018\u2019\u201A\u201B]/g, "'")
    .replace(/\u2026/g, '...')
    .replace(/[\u200B\u200C\u200D\u2060\uFEFF]/g, '')
    .replace(/\u00A0/g, ' ')
    .replace(/\s*\u2192\s*/g, ' to ')
    .replace(/\s*\u2190\s*/g, ' from ')
    .replace(/\s*[\u2191\u2193]\s*/g, ' ')
    .replace(/\s*[\u00B7\u2022]\s*/g, ' | ')
    .replace(/\u20B9/g, 'Rs ')
    .replace(/\u20AC/g, 'EUR ')
    .replace(/\u00A3/g, 'GBP ')
    .replace(/\s+/g, ' ')
    .trim();
}

function textRun(text, options = {}) {
  return new TextRun({ text: normalizeCvTextForAts(text), size: 21, font: 'Arial', ...options });
}

export function markdownToDocxParagraphs(markdown) {
  const paragraphs = [];
  for (const rawLine of String(markdown || '').split(/\r\n|\n|\r/)) {
    const trimmed = rawLine.trim();
    if (!trimmed || /^-{3,}$/.test(trimmed)) continue;
    if (trimmed.startsWith('# ')) {
      paragraphs.push(new Paragraph({ children: [textRun(trimmed.slice(2), { bold: true, size: 32 })], spacing: { after: 140 } }));
      continue;
    }
    if (trimmed.startsWith('## ')) {
      paragraphs.push(new Paragraph({ children: [textRun(trimmed.slice(3).toUpperCase(), { bold: true, color: '1D6F7A', size: 22 })], heading: HeadingLevel.HEADING_2, spacing: { before: 160, after: 80 } }));
      continue;
    }
    if (trimmed.startsWith('### ')) {
      paragraphs.push(new Paragraph({ children: [textRun(trimmed.slice(4), { bold: true })], heading: HeadingLevel.HEADING_3, spacing: { before: 120, after: 40 } }));
      continue;
    }
    if (/^[-*]\s+/.test(trimmed)) {
      paragraphs.push(new Paragraph({ children: [textRun(trimmed.replace(/^[-*]\s+/, ''))], bullet: { level: 0 }, spacing: { after: 40 } }));
      continue;
    }
    paragraphs.push(new Paragraph({ children: [textRun(trimmed)], spacing: { after: 80 } }));
  }
  return paragraphs;
}

export async function renderAtsDocx(markdown) {
  const document = new Document({
    creator: 'ApplyCue',
    title: 'ApplyCue tailored CV',
    description: 'Single-column ATS-friendly CV generated by ApplyCue.',
    sections: [{
      properties: { page: { margin: { top: 720, right: 720, bottom: 720, left: 720 } } },
      children: markdownToDocxParagraphs(markdown)
    }]
  });
  return Packer.toBuffer(document);
}

async function main() {
  const [inputArg, outputArg] = process.argv.slice(2);
  if (!inputArg || !outputArg) {
    console.error('Usage: node generate-docx.mjs <tailored-cv.md> <output.docx>');
    process.exit(1);
  }
  const input = resolve(inputArg);
  const output = resolve(outputArg);
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, await renderAtsDocx(readFileSync(input, 'utf8')));
  console.log(`Generated ${output}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  main().catch((error) => { console.error(error.message); process.exit(1); });
}
